<a href="https://colab.research.google.com/github/sandeeproyy/ML-Notes/blob/main/Numpy_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from time import process_time

Timetaken by a list

In [ ]:
python_list = [ i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0006752169999995061


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00014594700000003513


Numpy Arrays

In [ ]:
 list1 = [1,2,3,4,5]
 print(list1)
 type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating a 1 dim array

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Placeholders in Array
Initial Placeholders

```
# This is formatted as code
```



In [ ]:
#create a numpy array of zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array with alll value = 1

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular vaue
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# identity matrix with np
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# creata np array with random values
b = np.random.random((3,5))
print(b)

[[0.16543236 0.98832226 0.58486704 0.54081491 0.15528611]
 [0.69948747 0.06634868 0.99760481 0.84616718 0.56939548]
 [0.02282028 0.87283957 0.03093521 0.47595466 0.35927116]]


In [ ]:
# random values with integers
c = np.random.randint(10,100,(5,6))
print(c)

[[93 95 44 74 80 72]
 [49 36 13 50 35 68]
 [40 92 28 48 30 86]
 [74 91 38 49 16 74]
 [41 67 71 59 50 55]]


In [ ]:
 #array of evenly spaced values -- specifying number of value required
 d = np.linspace(10,30,5)
 print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --. specifying the steps
e = np.arange(20,30,5)
print(e)

[20 25]


In [ ]:
# convert a list to an numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a Numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[55 48 77 47 31]
 [29 32 80 33 60]
 [34 73 59 22 34]
 [84 73 68 16 53]
 [79 78 68 27 79]]


In [ ]:
# array dimensions
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
#number of elements in an array
print(c.size)

25


In [ ]:
# check the data typeof the values in the array
print(c.dtype)

int64


Mathematical Operations on an np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    #concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b= np.random.randint(10,20,(3,3))

print(a)
print(b)

[[4 1 9]
 [4 0 1]
 [5 9 8]]
[[13 17 18]
 [15 17 11]
 [17 17 15]]


In [ ]:
print(a + b)   #does not concatenate, element wise addition happens (all element wise opeartions)
print(a - b)
print(a*b)
print(a / b)

[[17 18 27]
 [19 17 12]
 [22 26 23]]
[[ -9 -16  -9]
 [-11 -17 -10]
 [-12  -8  -7]]
[[ 52  17 162]
 [ 60   0  11]
 [ 85 153 120]]
[[0.30769231 0.05882353 0.5       ]
 [0.26666667 0.         0.09090909]
 [0.29411765 0.52941176 0.53333333]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b= np.random.randint(10,20,(3,3))
print(a,b)
print(np.add(a,b))

[[2 6 7]
 [9 1 3]
 [6 6 7]] [[16 10 11]
 [16 10 16]
 [19 13 19]]
[[18 16 18]
 [25 11 19]
 [25 19 26]]


In [ ]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[-11 -16  -9]
 [ -8 -17 -11]
 [-13  -6 -12]]
[[ 60  36  52]
 [128   0  60]
 [114  72  64]]
[[0.26666667 0.11111111 0.30769231]
 [0.5        0.         0.26666667]
 [0.31578947 0.5        0.25      ]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 4 0]
 [3 3 8]]
(2, 3)


In [ ]:
# Transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[8 3]
 [4 3]
 [0 8]]
(3, 2)


In [ ]:
# another way of finding transpose
trans2 = array.T  #just add T after the Matrix u wanna transpose
print(trans2)
print(trans2.shape)

[[8 3]
 [4 3]
 [0 8]]
(3, 2)


Reshaping an Array

In [ ]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 4 6]
 [6 1 7]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 4]
 [6 6]
 [1 7]]
(3, 2)
